"""
NOVUS CLI.

Command-line interface for interacting with NOVUS.
"""

from __future__ import annotations

import asyncio
import sys
from typing import Optional
import structlog

import typer
import click
from rich.console import Console
from rich.table import Table
from rich.progress import Progress, SpinnerColumn, TextColumn
from rich import print as rprint

from novus.swarm.orchestrator import SwarmOrchestrator
from novus.core.models import SwarmConfig, AgentCapability
from novus.world_model.engine import WorldModel, WorldModelPlanner

# Rich console
console = Console()

# Create app
app = typer.Typer(
    name="novus",
    help="NOVUS: Next-Generation Agentic AI Platform",
    add_completion=False
)

logger = structlog.get_logger()


@app.command()
def start(
    agents: int = typer.Option(5, "--agents", "-a", help="Number of agents to start"),
    port: int = typer.Option(8000, "--port", "-p", help="API server port"),
    host: str = typer.Option("0.0.0.0", "--host", help="API server host"),
    evolve: bool = typer.Option(False, "--evolve", help="Enable evolutionary optimization"),
):
    """Start the NOVUS API server."""
    from novus.api.server import app as fastapi_app
    import uvicorn
    
    console.print(f"[bold green]Starting NOVUS with {agents} agents...[/bold green]")
    
    # Run server
    uvicorn.run(
        fastapi_app,
        host=host,
        port=port,
        log_level="info"
    )


@app.command()
def swarm(
    agents: int = typer.Option(5, "--agents", "-a", help="Number of agents"),
    problem: str = typer.Option(..., "--problem", "-p", help="Problem to solve"),
    evolve: bool = typer.Option(False, "--evolve", help="Enable evolution"),
):
    """Solve a problem using swarm intelligence."""
    
    async def _run():
        config = SwarmConfig(
            target_agent_count=agents,
            enable_evolution=evolve
        )
        
        swarm = SwarmOrchestrator(config)
        await swarm.start()
        
        console.print(f"[bold]Solving:[/bold] {problem}")
        
        with Progress(
            SpinnerColumn(),
            TextColumn("[progress.description]{task.description}"),
            console=console
        ) as progress:
            task = progress.add_task("Running swarm...", total=None)
            
            solution = await swarm.collective_solve(
                problem=problem,
                n_agents=min(agents, 5)
            )
        
        console.print("\n[bold green]Solution:[/bold green]")
        console.print(solution.content)
        console.print(f"\n[bold]Confidence:[/bold] {solution.confidence:.2%}")
        console.print(f"[bold]Generated by:[/bold] {solution.generated_by}")
        
        swarm.stop()
    
    asyncio.run(_run())


@app.command()
def status():
    """Show NOVUS system status."""
    
    async def _run():
        config = SwarmConfig(target_agent_count=3)
        swarm = SwarmOrchestrator(config)
        await swarm.start()
        
        status = swarm.get_status()
        
        # Display status
        table = Table(title="NOVUS Swarm Status")
        table.add_column("Metric", style="cyan")
        table.add_column("Value", style="green")
        
        table.add_row("Population", str(status["population"]))
        table.add_row("Generation", str(status["generation"]))
        table.add_row("Pending Tasks", str(status["pending_tasks"]))
        table.add_row("Active Tasks", str(status["active_tasks"]))
        table.add_row("Completed Tasks", str(status["completed_tasks"]))
        
        console.print(table)
        
        # Agent details
        if status["agents"]:
            agent_table = Table(title="Agents")
            agent_table.add_column("Name", style="cyan")
            agent_table.add_column("Status", style="green")
            agent_table.add_column("Active Tasks", style="yellow")
            agent_table.add_column("Fitness", style="magenta")
            
            for agent_id, info in status["agents"].items():
                agent_table.add_row(
                    info["name"],
                    info["status"],
                    str(info["active_tasks"]),
                    f"{info['fitness']:.2f}"
                )
            
            console.print(agent_table)
        
        swarm.stop()
    
    asyncio.run(_run())


@app.command()
def plan(
    goal: str = typer.Option(..., "--goal", "-g", help="Goal state as JSON"),
    initial: str = typer.Option(..., "--initial", "-i", help="Initial state as JSON"),
    max_steps: int = typer.Option(10, "--max-steps", help="Maximum plan length"),
):
    """Plan using world model simulation."""
    import json
    
    async def _run():
        try:
            goal_state = json.loads(goal)
            initial_state = json.loads(initial)
        except json.JSONDecodeError as e:
            console.print(f"[bold red]Error:[/bold red] Invalid JSON: {e}")
            raise typer.Exit(1)
        
        world_model = WorldModel()
        planner = WorldModelPlanner(world_model)
        
        console.print("[bold]Planning...[/bold]")
        
        result = await planner.plan(
            goal_state=goal_state,
            initial_state=initial_state,
            max_plan_length=max_steps
        )
        
        console.print(f"\n[bold green]Best Plan Score:[/bold green] {result['best_score']:.2f}")
        console.print(f"\n[bold]Best Plan:[/bold]")
        
        for i, action in enumerate(result["best_plan"], 1):
            console.print(f"  {i}. {action.get('type', 'unknown')}")
        
        if result["alternatives"]:
            console.print(f"\n[bold]Top Alternatives:[/bold]")
            for i, alt in enumerate(result["alternatives"][:3], 1):
                console.print(f"  {i}. Score: {alt['score']:.2f}")
    
    asyncio.run(_run())


@app.command()
def onboard(
    quick: bool = typer.Option(False, "--quick", "-q", help="QuickStart mode (defaults)"),
    advanced: bool = typer.Option(False, "--advanced", "-a", help="Advanced mode (full control)"),
    non_interactive: bool = typer.Option(False, "--non-interactive", help="Non-interactive mode"),
):
    """Interactive onboarding wizard - setup NOVUS with guided configuration."""
    from pathlib import Path
    import os
    
    console.print("[bold green]╔══════════════════════════════════════════╗[/bold green]")
    console.print("[bold green]║         NOVUS Onboarding Wizard          ║[/bold green]")
    console.print("[bold green]╚══════════════════════════════════════════╝[/bold green]")
    console.print()
    
    # Determine mode
    if non_interactive:
        mode = "quickstart"
    elif quick:
        mode = "quickstart"
    elif advanced:
        mode = "advanced"
    else:
        mode = typer.prompt(
            "Choose setup mode",
            type=click.Choice(["quickstart", "advanced"], case_sensitive=False),
            default="quickstart"
        )
    
    # Create NOVUS home directory
    novus_home = Path.home() / ".novus"
    novus_home.mkdir(exist_ok=True)
    
    # Create subdirectories
    dirs = ["knowledge", "logs", "cache", "sessions", "agents", "configs"]
    for d in dirs:
        (novus_home / d).mkdir(exist_ok=True)
    
    console.print(f"\n[bold]Step 1: Workspace[/bold]")
    console.print(f"Created directories: {', '.join(dirs)}")
    
    # Step 2: Identity (all modes)
    console.print(f"\n[bold]Step 2: Identity[/bold]")
    if non_interactive:
        name = "User"
        email = "user@example.com"
    else:
        name = typer.prompt("Your name", default="User")
        email = typer.prompt("Your email", default="user@example.com")
    
    # Step 3: API Keys (critical for functionality)
    console.print(f"\n[bold]Step 3: API Configuration[/bold]")
    console.print("[yellow]⚠️  API keys are required for NOVUS to function[/yellow]")
    
    api_keys = {}
    
    if mode == "advanced" or non_interactive:
        # Collect all provider keys in advanced mode
        providers = ["openai", "anthropic", "deepseek", "groq"]
        
        for provider in providers:
            env_var = f"{provider.upper()}_API_KEY"
            existing = os.environ.get(env_var)
            
            if existing:
                console.print(f"  ✓ {provider}: Found in environment ({env_var})")
                api_keys[provider] = existing
            elif non_interactive:
                console.print(f"  ⚠ {provider}: Not set (set {env_var} env var)")
            else:
                key = typer.prompt(
                    f"{provider.upper()} API key (optional, press Enter to skip)",
                    default="",
                    show_default=False,
                    hide_input=True
                )
                if key:
                    api_keys[provider] = key
                    console.print(f"  ✓ {provider}: Configured")
    else:
        # QuickStart - just get one key to get started
        console.print("\n[bold]Primary LLM Provider[/bold]")
        console.print("Choose your main AI provider (you can add more later):")
        
        provider = typer.prompt(
            "Provider",
            type=click.Choice(["openai", "anthropic", "skip"], case_sensitive=False),
            default="openai"
        )
        
        if provider != "skip":
            key = typer.prompt(
                f"{provider.upper()} API key",
                hide_input=True
            )
            if key:
                api_keys[provider] = key
                console.print(f"  ✓ {provider}: API key configured")
    
    # Store API keys securely
    if api_keys:
        keys_file = novus_home / "api-keys.yaml"
        with open(keys_file, "w") as f:
            f.write("# NOVUS API Keys\n")
            f.write("# IMPORTANT: Keep this file secure!\n\n")
            for provider, key in api_keys.items():
                # In production, these should be encrypted
                f.write(f"{provider}: \"{key[:8]}...{key[-4:]}\"\n")
        
        # Also create environment setup script
        env_file = novus_home / "env.sh"
        with open(env_file, "w") as f:
            f.write("#!/bin/bash\n# NOVUS Environment Setup\n\n")
            for provider, key in api_keys.items():
                f.write(f"export {provider.upper()}_API_KEY=\"{key}\"\n")
        os.chmod(env_file, 0o600)
        
        console.print(f"\n[green]API keys saved to {keys_file}[/green]")
        console.print(f"[dim]Environment script: {env_file}[/dim]")
    
    # Step 4: Preferences
    console.print(f"\n[bold]Step 4: Preferences[/bold]")
    if non_interactive:
        style = "direct"
        risk = "medium"
        auto_approve = False
    else:
        style = typer.prompt(
            "Communication style",
            type=click.Choice(["direct", "detailed", "casual"], case_sensitive=False),
            default="direct"
        )
        risk = typer.prompt(
            "Risk tolerance",
            type=click.Choice(["low", "medium", "high"], case_sensitive=False),
            default="medium"
        )
        auto_approve = typer.confirm("Auto-approve low-risk actions?", default=False)
    
    # Create identity file
    identity = f"""# NOVUS Identity
user:
  name: "{name}"
  email: "{email}"
  timezone: "UTC"

preferences:
  communication_style: "{style}"
  risk_tolerance: "{risk}"
  auto_approve: {str(auto_approve).lower()}

safety:
  require_approval_for:
    - code_execution
    - network_calls
    - file_deletion
    - external_api_calls
  auto_approve_below_cost: 0.50
"""
    
    identity_file = novus_home / "identity.yaml"
    with open(identity_file, "w") as f:
        f.write(identity)
    
    console.print(f"\n[green]✓ Identity saved: {identity_file}[/green]")
    
    # Step 5: Advanced settings (advanced mode only)
    if mode == "advanced" and not non_interactive:
        console.print(f"\n[bold]Step 5: Advanced Settings[/bold]")
        
        swarm_size = typer.prompt(
            "Default swarm size (number of agents)",
            type=int,
            default=5
        )
        
        enable_evolution = typer.confirm(
            "Enable agent evolution?",
            default=False
        )
        
        enable_guardrails = typer.confirm(
            "Enable safety guardrails?",
            default=True
        )
        
        # Write advanced config
        config_file = novus_home / "config.yaml"
        config_content = f"""# NOVUS Configuration
swarm:
  target_agent_count: {swarm_size}
  enable_evolution: {str(enable_evolution).lower()}

safety:
  enable_guardrails: {str(enable_guardrails).lower()}
  max_execution_time: 30
  allow_code_execution: true

memory:
  max_entries: 10000
  enable_engram: true
"""
        with open(config_file, "w") as f:
            f.write(config_content)
        
        console.print(f"[green]✓ Config saved: {config_file}[/green]")
    
    # Step 6: Health check
    console.print(f"\n[bold]Step 6: Health Check[/bold]")
    
    checks = []
    
    # Check Python version
    import sys
    py_version = sys.version_info
    py_ok = py_version >= (3, 11)
    checks.append(("Python 3.11+", "✅" if py_ok else "❌"))
    
    # Check directories
    checks.append(("Config directory", "✅"))
    
    # Check identity
    checks.append(("Identity file", "✅"))
    
    # Check API keys
    has_keys = len(api_keys) > 0
    checks.append(("API keys configured", "✅" if has_keys else "⚠️ "))
    
    # Check optional dependencies
    try:
        import fastapi
        checks.append(("FastAPI", "✅"))
    except ImportError:
        checks.append(("FastAPI", "❌"))
    
    try:
        import playwright
        checks.append(("Playwright (optional)", "✅"))
    except ImportError:
        checks.append(("Playwright (optional)", "⚠️ "))
    
    for check, status in checks:
        console.print(f"  {status} {check}")
    
    # Final summary
    console.print(f"\n[bold green]╔══════════════════════════════════════════╗[/bold green]")
    console.print(f"[bold green]║     Onboarding Complete! 🎉              ║[/bold green]")
    console.print(f"[bold green]╚══════════════════════════════════════════╝[/bold green]")
    console.print()
    console.print(f"[dim]Configuration directory:[/dim] {novus_home}")
    console.print()
    console.print("[bold]Next steps:[/bold]")
    
    if not has_keys:
        console.print("  1. [yellow]Set API keys:[/yellow]")
        console.print("     export OPENAI_API_KEY=sk-...")
        console.print("     export ANTHROPIC_API_KEY=sk-ant-...")
    else:
        console.print("  1. Source environment: source ~/.novus/env.sh")
    
    console.print("  2. Test installation: novus doctor")
    console.print("  3. Run first task: novus swarm 'What is 15 * 23?'")
    console.print("  4. Start API server: novus start")
    console.print()
    console.print("[dim]Documentation: https://docs.novus.ai[/dim]")
    console.print("[dim]Support: https://discord.gg/novus[/dim]")


@app.command()
def init():
    """Initialize a new NOVUS project (legacy, use 'onboard' instead)."""
    console.print("[yellow]⚠️  'novus init' is deprecated.[/yellow]")
    console.print("[yellow]   Use 'novus onboard' instead.[/yellow]")
    onboard(quick=True, non_interactive=True)


def main():
    """Main entry point."""
    try:
        app()
    except KeyboardInterrupt:
        console.print("\n[yellow]Interrupted[/yellow]")
        sys.exit(0)
    except Exception as e:
        console.print(f"[bold red]Error:[/bold red] {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
