#!/usr/bin/env python3
"""
Example: Basic NOVUS Usage

Demonstrates how to create a swarm and solve a problem.
"""

import asyncio
from novus.swarm.orchestrator import SwarmOrchestrator
from novus.core.models import SwarmConfig, Task, AgentCapability


async def basic_usage():
    """Basic swarm usage example."""
    print("=" * 60)
    print("NOVUS Basic Usage Example")
    print("=" * 60)
    
    # Create swarm configuration
    config = SwarmConfig(
        target_agent_count=5,
        enable_evolution=False  # Disable for demo
    )
    
    # Initialize orchestrator
    swarm = SwarmOrchestrator(config)
    await swarm.start()
    
    print(f"\nSwarm started with {len(swarm.agents)} agents")
    
    # Example 1: Submit a simple task
    print("\n--- Example 1: Simple Task ---")
    task = Task(
        description="What is the capital of France?",
        required_capabilities={AgentCapability.REASONING}
    )
    
    await swarm.submit_task(task)
    result = await swarm.get_task_result(task.id, timeout=10.0)
    
    print(f"Task ID: {task.id}")
    print(f"Status: {result.status if result else 'timeout'}")
    print(f"Result: {result.result if result else 'N/A'}")
    
    # Example 2: Collective problem solving
    print("\n--- Example 2: Collective Solve ---")
    problem = "Explain how photosynthesis works"
    
    solution = await swarm.collective_solve(
        problem=problem,
        n_agents=3,
        consensus_threshold=0.75
    )
    
    print(f"Problem: {problem}")
    print(f"Solution: {solution.content[:200]}...")
    print(f"Confidence: {solution.confidence:.2%}")
    print(f"Generated by: {solution.generated_by}")
    
    # Example 3: Check swarm status
    print("\n--- Example 3: Swarm Status ---")
    status = swarm.get_status()
    
    print(f"Population: {status['population']}")
    print(f"Generation: {status['generation']}")
    print(f"Pending tasks: {status['pending_tasks']}")
    print(f"Active tasks: {status['active_tasks']}")
    print(f"Completed tasks: {status['completed_tasks']}")
    
    print("\nAgents:")
    for agent_id, info in status['agents'].items():
        print(f"  - {info['name']}: {info['status']} (tasks: {info['active_tasks']}, fitness: {info['fitness']:.2f})")
    
    # Cleanup
    swarm.stop()
    print("\n" + "=" * 60)
    print("Example completed!")
    print("=" * 60)


if __name__ == "__main__":
    asyncio.run(basic_usage())
